In [ ]:
import pandas as pd

df = pd.read_csv("../data/raw/construction_cost_dataset_50_projects.csv")

df

(50, 11)

In [4]:
df.shape

(50, 11)

In [5]:
df.head()

,Project_ID,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Building_Type,Location,Foundation_Type,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT,Total_Cost_crore_BDT
0,1,7038,17800,5,Commercial,Dhaka,Pile,16.7,4.10,1.71,7.44
1,2,2060,4300,4,Residential,Other City,Isolated Footing,8.5,0.88,0.38,1.34
2,3,6627,35900,8,Residential,Dhaka,Isolated Footing,28.5,8.00,2.78,11.92
3,4,4912,14200,5,Commercial,Other City,Raft,18.7,4.02,1.19,6.11
4,5,6322,34500,8,Commercial,Other City,Pile,29.4,7.40,2.52,11.21

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Project_ID               50 non-null     int64
 1   Land_Area_sqft           50 non-null     int64
 2   Total_Floor_Area_sqft    50 non-null     int64
 3   Number_of_Floors         50 non-null     int64
 4   Building_Type            50 non-null     str
 5   Location                 50 non-null     str
 6   Foundation_Type          50 non-null     str
 7   Project_Duration_months  50 non-null     float64
 8   Material_Cost_crore_BDT  50 non-null     float64
 9   Labour_Cost_crore_BDT    50 non-null     float64
 10  Total_Cost_crore_BDT     50 non-null     float64
dtypes: float64(4), int64(4), str(3)
memory usage: 4.4 KB

In [7]:
df.describe()

,Project_ID,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT,Total_Cost_crore_BDT
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,25.50000,5845.640000,27746.000000,7.740000,23.972000,6.914000,2.391800,10.669200
std,14.57738,2137.518309,15150.890187,2.464524,8.769475,3.999024,1.377541,6.022319
min,1.00000,2057.000000,4300.000000,4.000000,8.500000,0.880000,0.380000,1.340000
25%,13.25000,3800.000000,16250.000000,5.250000,16.250000,3.960000,1.290000,6.220000
50%,25.50000,6420.000000,28450.000000,7.500000,24.650000,6.650000,2.415000,10.610000
75%,37.75000,7358.000000,37550.000000,10.000000,29.375000,8.747500,3.202500,13.957500
max,50.00000,8963.000000,68900.000000,12.000000,44.900000,16.970000,6.850000,27.920000

In [8]:
df.isnull().sum()

Project_ID                 0
Land_Area_sqft             0
Total_Floor_Area_sqft      0
Number_of_Floors           0
Building_Type              0
Location                   0
Foundation_Type            0
Project_Duration_months    0
Material_Cost_crore_BDT    0
Labour_Cost_crore_BDT      0
Total_Cost_crore_BDT       0
dtype: int64